"""Exporters: LDraw (.ldr) for real Lego CAD tools, and a standalone bpy
script that rebuilds the model as geometry in Blender."""

from __future__ import annotations

from .catalog import COLORS
from .engine import Build, Piece

# LDraw units: 1 stud = 20 LDU in x/z, 1 plate = 8 LDU in y (y points DOWN).
# Most brick/plate/tile parts have their origin at the center of the top face.
_STUD = 20
_PLATE = 8


def to_ldraw(build: Build) -> str:
    lines = [f"0 {build.name}", "0 Name: {}.ldr".format(build.name.replace(" ", "_")),
             "0 Author: lego-mcp", "0 BFC CERTIFY CCW"]
    for p in sorted(build.pieces.values(), key=lambda p: (p.z, p.id)):
        color = COLORS[p.color][1]
        cx = (p.x + p.w / 2) * _STUD
        cz = (p.y + p.d / 2) * _STUD
        cy = -p.top * _PLATE
        # Slope facing may be flipped 180 vs LDraw's canonical orientation;
        # positions are exact, headings are approximate for sloped parts.
        rot = {0: "1 0 0 0 1 0 0 0 1",
               90: "0 0 -1 0 1 0 1 0 0",
               180: "-1 0 0 0 1 0 0 0 -1",
               270: "0 0 1 0 1 0 -1 0 0"}[p.rotation]
        lines.append(f"1 {color} {cx:g} {cy:g} {cz:g} {rot} {p.part.ldraw_id}.dat")
    return "\n".join(lines) + "\n"


def _bbox(cells: set[tuple[int, int]]) -> tuple[int, int, int, int]:
    xs = [c[0] for c in cells]
    ys = [c[1] for c in cells]
    return min(xs), min(ys), max(xs) - min(xs) + 1, max(ys) - min(ys) + 1


def _piece_dict(p: Piece) -> dict:
    part = p.part
    d = {"id": p.id, "part": p.part_name, "z": p.z, "h": part.height,
         "color": p.color, "studs": sorted(p.stud_cells),
         "body": None, "wedge": None}
    if not part.slope_rows:
        d["body"] = [p.x, p.y, p.w, p.d]
        return d
    # Split a slope into a full-height body (the stud/tall rows) and a wedge.
    body_cells = {p.local_to_world(i, j)
                  for i in range(part.width)
                  for j in range(part.depth - part.slope_rows)}
    wedge_cells = {p.local_to_world(i, j)
                   for i in range(part.width)
                   for j in range(part.depth - part.slope_rows, part.depth)}
    d["body"] = list(_bbox(body_cells))
    wx, wy, ww, wd = _bbox(wedge_cells)
    # Wedge template descends toward local +y; rotate it to the world heading.
    angle = {0: 0, 90: -90, 180: 180, 270: 90}[p.rotation]
    across, along = (ww, wd) if p.rotation in (0, 180) else (wd, ww)
    d["wedge"] = {"cx": wx + ww / 2, "cy": wy + wd / 2,
                  "across": across, "along": along,
                  "angle": angle, "inverted": part.inverted}
    return d


def to_blender_script(build: Build) -> str:
    """Standalone bpy script: brick bodies, wedges for slopes, stud cylinders.

    Uses data-level mesh copies of shared template meshes (no bpy.ops), so
    builds with thousands of pieces import in well under a second.
    """
    hexes = {name: hexval for name, (hexval, _) in COLORS.items()}
    pieces = [_piece_dict(p)
              for p in sorted(build.pieces.values(), key=lambda p: (p.z, p.id))]
    return f'''import math

import bmesh
import bpy

# Generated by lego-mcp from build "{build.name}" ({len(pieces)} pieces)
PIECES = {pieces!r}
HEX = {hexes!r}
STUD = 0.8   # 1 stud = 8mm -> 0.8 Blender units (cm scale)
PLATE = 0.32 # 1 plate = 3.2mm
LIP = 0.15   # front lip of a slope, as a fraction of unit height

coll = bpy.data.collections.get("{build.name}")
if coll is None:
    coll = bpy.data.collections.new("{build.name}")
    bpy.context.scene.collection.children.link(coll)


def template(name, verts, faces):
    mesh = bpy.data.meshes.new(name)
    bm = bmesh.new()
    vs = [bm.verts.new(v) for v in verts]
    for f in faces:
        bm.faces.new([vs[i] for i in f])
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(mesh)
    bm.free()
    return mesh


def cube_template():
    mesh = bpy.data.meshes.new("lego_tpl_cube")
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    bm.to_mesh(mesh)
    bm.free()
    return mesh


def stud_template():
    mesh = bpy.data.meshes.new("lego_tpl_stud")
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, segments=24,
                          radius1=0.24, radius2=0.24, depth=0.17)
    bm.to_mesh(mesh)
    bm.free()
    return mesh


cube = cube_template()
stud_tpl = stud_template()
# Unit wedge: full height at -y, descending to a small lip at +y.
wedge = template("lego_tpl_wedge",
    [(-.5, -.5, -.5), (.5, -.5, -.5), (.5, .5, -.5), (-.5, .5, -.5),
     (-.5, -.5, .5), (.5, -.5, .5),
     (-.5, .5, -.5 + LIP), (.5, .5, -.5 + LIP)],
    [(0, 1, 2, 3), (0, 1, 5, 4), (3, 2, 7, 6),
     (0, 4, 6, 3), (1, 2, 7, 5), (4, 5, 7, 6)])
# Inverted wedge: full top, underside rising from -y toward a lip at +y top.
wedge_inv = template("lego_tpl_wedge_inv",
    [(-.5, -.5, .5), (.5, -.5, .5), (.5, .5, .5), (-.5, .5, .5),
     (-.5, -.5, -.5), (.5, -.5, -.5),
     (-.5, .5, .5 - LIP), (.5, .5, .5 - LIP)],
    [(0, 1, 2, 3), (0, 1, 5, 4), (3, 2, 7, 6),
     (0, 4, 6, 3), (1, 2, 7, 5), (4, 5, 7, 6)])


def material(cname):
    mname = "lego_" + cname
    mat = bpy.data.materials.get(mname)
    if mat is None:
        mat = bpy.data.materials.new(mname)
        mat.use_nodes = True
        h = HEX[cname].lstrip("#")
        rgb = tuple(int(h[i:i+2], 16) / 255 for i in (0, 2, 4))
        srgb = tuple(c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
                     for c in rgb)
        bsdf = mat.node_tree.nodes["Principled BSDF"]
        bsdf.inputs["Base Color"].default_value = (*srgb, 1.0)
        bsdf.inputs["Roughness"].default_value = 0.18
    return mat


def spawn(tpl, name, mat, location, scale, rot_z=0.0):
    mesh = tpl.copy()
    mesh.name = name
    mesh.materials.append(mat)
    obj = bpy.data.objects.new(name, mesh)
    obj.location = location
    obj.scale = scale
    obj.rotation_euler = (0.0, 0.0, math.radians(rot_z))
    bev = obj.modifiers.new("Bevel", "BEVEL")
    bev.width = 0.01
    bev.segments = 2
    coll.objects.link(obj)
    return obj

for pc in PIECES:
    mat = material(pc["color"])
    h = pc["h"] * PLATE
    zc = pc["z"] * PLATE + h / 2
    name = "{build.name}_%03d_%s" % (pc["id"], pc["part"])
    anchor = None
    if pc["body"]:
        bx, by, bw, bd = pc["body"]
        anchor = spawn(cube, name, mat,
                       ((bx + bw / 2) * STUD, (by + bd / 2) * STUD, zc),
                       (bw * STUD * 0.995, bd * STUD * 0.995, h * 0.995))
    if pc["wedge"]:
        wg = pc["wedge"]
        tpl = wedge_inv if wg["inverted"] else wedge
        spawn(tpl, name + "_slope", mat,
              (wg["cx"] * STUD, wg["cy"] * STUD, zc),
              (wg["across"] * STUD * 0.995, wg["along"] * STUD * 0.995,
               h * 0.995),
              rot_z=wg["angle"])
    top = pc["z"] * PLATE + h
    for sx, sy in pc["studs"]:
        spawn(stud_tpl, name + "_stud", mat,
              ((sx + 0.5) * STUD, (sy + 0.5) * STUD, top + 0.085),
              (1.0, 1.0, 1.0))

print("lego-mcp: built %d pieces into collection {build.name}" % len(PIECES))
'''
